on:
#   watch:
#     types: started
#   push:
#     branches: [ main ]
  schedule:
    # Runs at 0am IST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
#     if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           SHOW_PROFILE_VIEWS: "True"
#           SHOW_LINES_OF_CODE: "True"
#           SHOW_COMMIT: "False"
#           SHOW_DAYS_OF_WEEK: "False"
#           SHOW_SHORT_INFO: "False"
#           SHOW_LOC_CHART: "False"
